server:
  port: 8080

logging:
  level:
    com:
      one: debug
#    org:
#      apache:
#        coyote:
#          http11: debug

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/one
    username: root
    password: qwer1234
  redis:
    host: localhost
    port: 49153
    password: redispw
  servlet:
    multipart:
      max-file-size: 1MB
      enabled: true

mybatis:
#  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

sms:
  api-key: NCSXDYZQTONF5TWN
  api-secret: STIMLW3DKBOVRWPITUQQIAW7M6Y5W96L
  from: "01071497833"

file:
  dir: /Users/bejim/file/